/**
 * OEIVAL Manufacturer Code → friendly Manufacturer Name mapping.
 *
 * Authoritative source: JMK's OEIVAL CSV export (every code/name pair
 * is built from there). Regenerated 2026-05-21 from the
 * `All IET-oeival 052126.csv` in-stock subset — see
 * aws/dunlop-reporter/lambdas/oeival_processor.py for the cache that
 * other consumers can pull from.
 *
 * The inventory route already reads CSV's manufacturerName directly
 * (idempotent through brandCodeToName); this map matters for the
 * OEA07V sales-side and any UI that has only a code in hand.
 */
export const BRAND_MAP: Record<string, string> = {
  "AC": "ACCELERA",
  "ACHIL": "ACHILLES",
  "ADV": "ADVANCE",
  "AGS": "AGSTAR",
  "AIR": "AIR-LOC",
  "AKU": "AKURET",
  "AL": "ALLIANCE",
  "AM": "AMERICUS",
  "AMP": "AMERITYRE",
  "AMT": "AMERITYRE",
  "AMU": "AMULET",
  "ANT": "ANTARES",
  "APL": "APLUS",
  "APT": "APTANY",
  "ARC": "ARCTIC CLAW",
  "ARI": "ARISUN",
  "ARM": "ARMSTRONG",
  "AROY": "ARROYO",
  "ARS": "AMERICAN ROADSTAR",
  "ASP": "ASPEN",
  "AST": "ASTRO",
  "ATF": "ATF",
  "ATL": "ATLAS",
  "ATT": "ATTURO",
  "ATU": "AMERICAN TOURER",
  "AV": "ADVANTA",
  "BCK": "BUCKSHOT",
  "BFG": "BF GOODRICH",
  "BK": "BKT",
  "BLK": "BLACKHAWK",
  "BRIDG": "BRIDGESTONE",
  "BU": "BUCKSHOT",
  "CA": "CARGO MASTER",
  "CAM": "CAMBRIDGE",
  "CARL": "CARLISLE",
  "CEL": "CELIMO",
  "CEN": "CENTENNIAL",
  "CMAS": "CROP MASTER",
  "CNV": "CONVERSE",
  "CO": "CARGO MAX",
  "CON": "CONTINENTAL",
  "COO": "COOPER",
  "COS": "COSMO",
  "CRK": "CASTLE ROCK",
  "CRM": "CROSSMAX",
  "CRW": "CARAWAY",
  "CTA": "CENTARA",
  "CW": "COUNTRYWIDE",
  "CWN": "CROSSWIND",
  "CX": "CROP MAX",
  "DBC": "DOUBLE COIN",
  "DBS": "DOUBLESTAR",
  "DCE": "DCENTI",
  "DEE": "DEESTONE",
  "DEL": "DELTA",
  "DELIN": "DELINTE",
  "DEM": "DELIUM",
  "DO": "DURO",
  "DOR": "DORAL",
  "DOU": "DOUGLAS",
  "DRN": "DURUN",
  "DUN": "DUNLOP",
  "DXT": "DEXTERO",
  "DYT": "DYNATRAC",
  "ELDO": "ELDORADO",
  "EVX": "EVOLUXX",
  "FAL": "FALKEN",
  "FED": "FEDERAL",
  "FHL": "FREEDOM HAULER",
  "FIN": "FINALIST",
  "FIR": "FIRESTONE",
  "FL": "FORCELAND",
  "FLR": "FULLRUN",
  "FLW": "FULLWAY",
  "FOR": "FORGIATO",
  "FORC": "FORCEUM",
  "FORT": "FORTUNE",
  "FRC": "FREE COUNTRY",
  "FRD": "FARROAD",
  "FREES": "FREESTAR",
  "FRN": "FERENTINO",
  "FRR": "FORERUNNER",
  "FUZ": "FUZION",
  "FY": "FURY",
  "GAL": "GALAXY",
  "GBC": "GBC",
  "GDR": "GEODRIVE",
  "GDY": "GOODYEAR",
  "GE": "GOODRIDE",
  "GEN": "GENERAL",
  "GL": "GLADIATOR",
  "GMM": "GREEN MAX",
  "GMS": "GRIT MASTER",
  "GMX": "GREMAX",
  "GNT": "GREENTRAC",
  "GPM": "GRIPMAX",
  "GREEN": "GREENBALL",
  "GRI": "GRI",
  "GRK": "GRIT KING",
  "GRM": "GREENMASTER",
  "GRO": "GROUNDSPEED",
  "GTR": "GOODTRIP",
  "GTRAD": "GT RADIAL",
  "GVN": "GIOVANNA",
  "HAIDA": "HAIDA",
  "HAN": "HANKOOK",
  "HEM": "HEMISPHERE",
  "HF": "HIFLY",
  "HKN": "HARVEST KING",
  "HR": "HI-RUN",
  "HRC": "HERCULES",
  "HSK": "HUSKY",
  "IET-P": "IET 'PART'",
  "IET-T": "IET 'TIRE'",
  "IM": "IMPERIAL",
  "INT": "INTERCO",
  "IRH": "IRONHEAD",
  "IRN": "IRONMAN",
  "IS": "IRIS",
  "IT": "ITP",
  "IVN": "INNOVA",
  "JKT": "JK TYRE",
  "KA": "KANATI",
  "KLY": "KELLY",
  "KN": "KENDA",
  "KNN": "K9",
  "KUMHO": "KUMHO",
  "LAN": "LANCASTER",
  "LEAO": "LEAO",
  "LEM": "LEMANS",
  "LFN": "LAUFENN",
  "LG": "LANDGOLDEN",
  "LION": "LIONHART",
  "LL": "LINGLONG",
  "LM": "LOADMAXX",
  "LNS": "LANDSAIL",
  "LR": "LANDSPIDER",
  "LVR": "LANVIGATOR",
  "LXN": "LEXANI",
  "MAX": "MAXXIS",
  "MAXA": "MAXAM",
  "MAXTR": "MAXTREK",
  "MC": "MASTERCRAFT",
  "MF": "MASSFX",
  "MI": "MICHELIN",
  "MICK": "MICKEY THOMPSON",
  "MIL": "MILESTAR",
  "MLK": "MILEKING",
  "MLP": "MILE PRO",
  "MLT": "MULTI MILE",
  "MOMO": "MOMO",
  "MONT": "MONTREAL",
  "MR": "MRF",
  "MRL": "MRL",
  "MTR": "MASTERTRACK",
  "NAN": "NANKANG",
  "NANCO": "NANCO",
  "NE": "NEOTERRA",
  "NEB": "NEBULA",
  "NEX": "NEXEN",
  "NI": "NITTO",
  "NM": "NAMA",
  "NOK": "NOKIAN",
  "NTC": "NUTECH",
  "NTN": "NATIONAL",
  "OHTSU": "OHTSU",
  "OM": "OMNI TRAIL",
  "ORT": "OMNI RECON TRAIL",
  "OTAN": "OTANI",
  "OTR": "OTR",
  "OX": "OMNIMAX",
  "PAT": "PATRIOT",
  "PEG": "PEGASUS",
  "PER": "PERFORMER",
  "PET": "PETLAS",
  "PI": "PREMIORRI",
  "PIN": "PINNACLE",
  "PIR": "PIRELLI",
  "PKN": "POWER KING",
  "PNT": "PANTERA",
  "POI": "POINT S",
  "PRE": "PREDATOR",
  "PRM": "PRIMEWELL",
  "PX": "PRINX",
  "QDB": "QUADBOSS",
  "RADAR": "RADAR",
  "RBL": "ROYAL BLACK",
  "RBP": "RBP",
  "RDC": "ROADCLAW",
  "RDM": "ROADMASTER",
  "RDT": "RED DIRT ROAD",
  "RDX": "ROADX",
  "RFL": "RED FLAME",
  "RGN": "REGENCY",
  "RLX": "ROADLUX",
  "RNW": "RUNWAY",
  "RO": "ROAD ONE",
  "ROV": "ROVELO",
  "RUB": "RUBBERMASTER",
  "RV": "ROVELO",
  "SAF": "SAFFIRO",
  "SAI": "SAILUN",
  "SAM": "SAMSON",
  "SCP": "SCEPTOR",
  "SDN": "SEDONA",
  "SE": "SENTURY",
  "SIG": "SIGMA",
  "SMM": "SUMMIT",
  "SNR": "SONAR",
  "SOL": "SOLAR",
  "SPC": "SUPERCARGO",
  "SPX": "SUPERMAX",
  "ST": "SURETRAC",
  "STF": "STARFIRE",
  "STG": "SUTONG",
  "STR": "STARMAXX",
  "STW": "STATEWIDE",
  "SUM": "SUMITOMO",
  "SUN": "SUNNY",
  "SYN": "SYNERGY",
  "TBB": "TBB",
  "TDR": "TERRA RAIDER",
  "TK": "TURNPIKE",
  "TKN": "TRAILER KING",
  "TLN": "ATLANDER",
  "TMM": "TRAILER MASTER",
  "TND": "THUNDERER",
  "TOR": "TORNEL",
  "TOW": "TOWMASTER",
  "TOY": "TOYO",
  "TRCGD": "TRAC GARD",
  "TRD-G": "TRD G",
  "TRD-P": "TRD MISC PART",
  "TRG": "TRAIL GUIDE",
  "TRI": "TRIANGLE",
  "TRR": "TRANSMASTER",
  "TRX": "TRANSMAX",
  "TSC": "TESCHE",
  "TSK": "TASKMASTER",
  "TTN": "TITAN",
  "TVS": "TRAVELSTAR",
  "TWS": "TOWSTAR",
  "UNI": "UNIROYAL",
  "VAL": "VALINO",
  "VLZ": "VELOZZA",
  "VN": "VENOM POWER",
  "VOG": "VOGUE",
  "VRC": "VERCELLI",
  "VRU": "VEE RUBBER",
  "VT": "VITOUR",
  "VTG": "VANTAGE",
  "VTY": "VERSATYRE",
  "VZ": "VIZZONI",
  "VZA": "VENEZIA",
  "WAN": "WANDA",
  "WDT": "WANDA",
  "WES": "WESTLAKE",
  "WF": "WATERFALL",
  "WNL": "WANLI",
  "WNR": "WINRUN",
  "YOK": "YOKOHAMA",
  "ZEE": "ZEEMAX",
  "ZET": "ZETA",
  "ZN": "ZENNA",
  "ZTX": "ZEETEX",
};

/**
 * Convert a brand code to full name.
 * Returns the full name if found, otherwise returns the code as-is.
 */
export function brandCodeToName(code: string): string {
  if (!code) return "";
  const upper = code.trim().toUpperCase();
  return BRAND_MAP[upper] || code;
}
